### ISSUE TITLE
how do i upload this project to ionic.io?

### ISSUE THREAD

**Issue by sathyaincampus** [DarrylD/react-ionic-redux#1]
how do i upload this project to ionic.io?
Usually with ionic, i do "ionic add platform android" and say "ionic upload". Can you tell me how I can upload the project created via your template to ionic and view that in the ionic-view app in android or ios?

**Comment by DarrylD** [comment]
@sathyaincampus this project was made before ionic.io, haven't updated it to used with it. I'm open to PR's if you're willing to work on it.

**Comment by DarrylD** [comment]
@sathyaincampus this project is pretty unofficial and wasn't made to be used in the ionic ecosystem. It was made to only use the js/css from ionic.

**Comment by sathyaincampus** [comment]
Thanks for the info @DarrylD
